name: asp-pangeo
channels:
  - conda-forge
dependencies:
  - nomkl
  - gcsfs=0.2
  - s3fs=0.2
  - intake=0.4
  - intake-xarray=0.3
  - curl=7.62
  - python=3.6
  - xarray=0.11
  - dask=1.0.0
  - distributed=1.25
  - matplotlib=3.0
  - nbserverproxy=0.8
  - jupyter=1.0
  - ipywidgets=7.4
  - graphviz=2.38
  - jupyterlab=0.35
  - nodejs=8.12
  - libgdal=2.4
  - boto3=1.9
  - hvplot=0.4
  - geoviews=1.6
  - datashader=0.6
  - requests=2.21
  - pandas=0.23
  - geopandas=0.4
  - dask-kubernetes=0.7
  - rasterio=1.0
  - pip:
    - wurlitzer
