#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz@0.6.4 \
                             jupyter-leaflet@0.10.0 \
                             dask-labextension@0.3.1

# Install Ames stereo pipeline in home folder
VERSION=StereoPipeline-2.6.1-2019-03-24-x86_64-Linux
wget -q https://byss.arc.nasa.gov/stereopipeline/daily_build/$VERSION.tar.bz2
tar -xjf $VERSION.tar.bz2
mv $VERSION /home/jovyan/StereoPipeline
rm $VERSION.tar.bz2

# doesn't work, need to set at beginning of notebook
#export PATH=/home/jovyan/StereoPipeline/bin:${PATH}

#EOF
